
GPS_POINT_DISTANCE = 15
TRAVEL_LENGTH_THRESHOLD = 5

INDEX_PLAN_TYPE = 0
INDEX_PLAN_LENGTH = 1
INDEX_PLAN_TRAVEL_DIR = 2
INDEX_PLAN_RADIUS = 3
INDEX_PLAN_START_LONGITUDE = 1
INDEX_PLAN_START_LATITUDE = 2
INDEX_PLAN_START_DIRECTION = 3


